### PR TITLE
Mv kmeans

### PR DESCRIPTION
**Pull request by astamm**
This PR provides extension of the k-means alignment algorithm to multivariate functional data, i.e. data with multi-dimensional codomain. It makes minimal modifications to a number of functions for this extension to happen. Also updates **testthat** version along the way and a number of documentation improvements. Details are in the commits.

### CODE REVIEW

**Comment by jdtuck** [comment]
So in a lot of cases multidimensional can be treated as open curves in R^n, which the curve code handles, why do you want to do duplicate most of this work over?

**Comment by astamm** [comment]
I did realise that R^d-valued functional data are already handled by some of the functions. I just thought that it could be nice to have the kmeans function also with this feature. It was relatively easy since it was *limited* to 1-d functional data because it forced the dimension to 1 in the C routines. If you accept the PR, I also plan to make the **fdacluster** package, formerly known as **fdakma**, depend on yours to include kmeans for functions defined on a fixed interval `[a,b]`.

About the doc update, it comes from the fact that I got confused many times with notations. Could not clearly picture in which dimension of the array to put the grid size or the sample size. So after a number of trials, I got it right and thought of improving the doc. I can do more if you want.

I was also thinking I could be of some help with improving code coverage. Could be good to switch from Travis CI to GitHub actions as well.

And I had some thoughts about the way parallelization is performed. I am a big fan of the futureverse framework. If you are interested, I could also contribute in this direction.

**Comment by astamm** [comment]
It seems the Travis CI is working under an old R version labelled as current release. My use of the pipe operator which appears in `R 4.1.x` fails. I can also not use the pipe operator which should solve this issue. But maybe it could be worth upgrading the release and devel versions of R on Travis.

**Comment by jdtuck** [comment]
Sounds good and I am good with your plan.

**Comment by jdtuck** [comment]
Also, we can update travis to fix the pipe error, feel free to make edits to the yml file

**Comment by jdtuck** [comment]
I appreciate any help on making the docs and going to github actions. All on my list, but higher priority things move them down. Thank you for all you have done in this PR. Also if we upgrade travis, lets upgrade which R is the minimum version to avoid any issues there.

**Comment by astamm** [comment]
If you are ok with that, we could switch to GHA and remove travis CI. There are ready-to-go GHA scripts with up-to-date R-release and R-devel versions that tests on a variety of OSes. Let me know. Could be a separate PR to keep things clearer. Same holds for doc improvements.

**Comment by jdtuck** [comment]
I am good with that

**Comment by astamm** [comment]
Good for me. I removed the pipe operator so this PR should pass the current Travis config.

**Comment by jdtuck** [comment]
Looks like you still have one

```
Error in parse(outFile) : 

  /home/travis/build/jdtuck/fdasrvf_R/fdasrvf.Rcheck/00_pkg_src/fdasrvf/R/kmeans.R:325:18: unexpected '>'

324:     tbl <- table(out$labels)

325:     cols <- idx |>

```

**Comment by jdtuck** [comment]
Though code looks good, travis must not have repulled correctly

**Comment by jdtuck** [comment]
Looks to be an issue with `data.R` fixing now

**Comment by astamm** [comment]
It seems it is still not happy with documentation which uses `\eqn{}` which used to transfer correctly to *html* version of the manual but not *PDF*. This is the reason I believe why Travis still complains. Newer versions of R now handles `\eqn{}` properly also for the PDF version of the manual. I could contribute in this PR the switch to GitHub actions with up-to-date R-release and -devel versions to confirm there are no relevant issues with the modifications done in this PR.

**Comment by astamm** [comment]
OK. This PR can be merged. I will contribute two other Prs: one for improving code coverage and one for transitioning to GHA for CI. Also code coverage calculation can be automated via GHA. Do you want me to add that as well?

**Comment by jdtuck** [comment]
Merging now and will wait for the PRs before next CRAN release

**Pull request merged**
