### PR TITLE
Improved distance (matrix) computation

### PR DESCRIPTION
**Pull request by astamm**
- fixes in `find_rotation_seed_unique()` and `find_rotation_seed_coord()`; penalty option is added for both;
- refactoring in `calc_shape_dist()` and `curve_dist()` using newly defined internal functions `curve_to_srvf()` and `match_f2_to_f1()`;
- New internal functions in `utils-pointwise.R`:
    -  `amplitude_distance()` computes the distance in amplitude between two SRVFs supposed optimally transformed;
    -  `phase_distance()` computes the distance in phase between two SRVFs assumed to be already optimally transformed using the estimated $\gamma$;
    - `pointwise_mean()` computes or updates the Karcher mean or median using a set of SRVFs assumed to be already optimally transformed.

These internal functions should be helpful in making the code for Karcher mean computation clearer in the near future.

- Fixes in `kmeans_align()` which was broken; still needs an update though; in a near future as well.

### CODE REVIEW

**Comment by jdtuck** [comment]
See code review above

**Comment by astamm** [comment]
Thanks but I do not see the review.

**Comment by jdtuck** [comment]
where did the centering go? This is a large PR so have had hard time going through the diff to find it if you moved it.

**Comment by jdtuck** [comment]
Is this ready to merge?

**Comment by jdtuck** [comment]
closes #44 and #42

**Comment by astamm** [comment]
Well it does pass current tests and should not break current user experience and should make one or two things faster.

**Comment by astamm** [comment]
In one of my commits, I added Closes #42 but I wouldn't close #44 as I have not yet done this.

**Pull request merged**
