### PR TITLE
Switch from travis appveyor to GHA for CI and code coverage monitoring.

### PR DESCRIPTION
**Pull request by astamm**

### CODE REVIEW

**Comment by astamm** [comment]
I am not sure how this PR can be checked. I configured the GHA scripts to target the main repo which is yours, which means I cannot trigger them.

**Comment by jdtuck** [comment]
yeah it won't, I will merge it and see what happens.

**Comment by jdtuck** [comment]
Take a look at the output when its done and we can work any changes.

**Comment by jdtuck** [comment]
Okay got it all working, thanks for the start :-)

**Comment by astamm** [comment]
Glad I could be of some help. I'll start the work on improving code coverage and doc along the way.

**Comment by jdtuck** [comment]
Sounds good. One question, would you like me to prepare a release for CRAN so you can link your package to it?

**Comment by astamm** [comment]
That would be much appreciated indeed. Thanks!

**Pull request merged**
